---
title: "Full Process Calculations"
output: html_notebook
---

## Set directory and libraries

```{r}
directory = 'E:/Documents/fair_shares_ds_projects/FS_P003_Customer_Order_List'
setwd(directory)

library(tidyverse)
library(DT)
library(googlesheets4)
library(openxlsx)
library(emoji)
library(emo)
```

## load data file

```{r}
file_name = 'Member Pick-up Details-03_23_2022.csv'
# file_name = 'Member Pick-up Details-06_09_2021.csv'
df_orig = read.csv(paste0(directory,'/farmigo_downloads/',file_name)) |> 
  rename_all(tolower) |> 
  rename(group_name = pickup.site, firstname = first.name, lastname = last.name) |> 
  mutate(id = row_number())
```

## connect to settings sheet

```{r}
gs4_auth(email = "")
```

## load settings data

```{r}
sh_shares = range_read('1pEEGA3mawQWmgDtIjJmpBMPws8_-EyEqPtQlucGVlNQ'
                ,sheet = 'shares'
                ,col_types = 'ccc--'
                ,skip = 1
)

sh_delete = range_read('1pEEGA3mawQWmgDtIjJmpBMPws8_-EyEqPtQlucGVlNQ'
                ,sheet = 'delete'
                ,col_types = 'c'
)
```

## Make data long and separate date to be processed without quantity

```{r}
df_orig_long = df_orig  |>  
  mutate(order = strsplit(as.character(order), ",")) |>
  unnest(order) |> 
  mutate(pickuptime = ifelse(str_detect(order, "Pickup Time"), 2, NA),
         order = trimws(order)) |> 
  separate(order, into = c('quantity','item'), sep = 'x', extra = "merge") |> 
  mutate(item = ifelse(is.na(item) & !is.na(quantity), quantity, item)
         ,quantity = ifelse(item == quantity, NA, quantity)
         ,group_bool = ifelse(is.na(quantity) & !is.na(item), 1, NA)
         ,rank = ifelse(!is.na(group_bool), group_bool,
                        ifelse(!is.na(pickuptime), pickuptime, 3))
         ,name_long = paste0(lastname,', ',firstname,' [',id,']')
         ) |> 
  select(-group_bool, -pickuptime) |> 
  rbind(df_orig |> #bringing in a new row for each group_name
          select(group_name) |> 
          distinct() |> 
          mutate(firstname = '0'
                 ,lastname = '0'
                 ,quantity = NA
                 ,item = group_name
                 ,id = 0
                 ,rank = -1
                 ,name_long = paste0(lastname,', ',firstname,' [',id,']')
                  )
        ) |> 
    rbind(df_orig |> #bringing in a new row for each member name
          select(group_name, firstname, lastname, id) |> 
          distinct() |> 
          mutate(quantity = NA
                 ,item = paste0(lastname,', ',firstname)
                 ,rank = 0
                 ,name_long = paste0(lastname,', ',firstname,' [',id,']')
                  ) |> 
          select(group_name, firstname, lastname, quantity, item, id, rank, name_long)
        ) |> 
  arrange(group_name, lastname, firstname, id, rank) 

df_orig_long

```

## Pickup Times found

```{r}
pickup_time = df_orig_long |> 
  filter(rank == 2) |> 
  group_by(Time = item) |> 
  summarise(count = n()) |> 
  ungroup() |> 
  mutate(val = Time) |> 
  separate(val, into = c('q','time','description'), sep = ' ', extra = "merge") |> 
  arrange(description, time, q) 

pickup_time_counts = pickup_time |> 
  select(Time, count)

pickup_time_counts

df_long_tm = df_orig_long |> 
  left_join(
    df_orig_long |> 
      filter(rank == 2) |> 
      select(id, item) |> 
      distinct() |> 
      left_join(pickup_time |> 
                  select(item = Time, description, time)
                , by = c('item')
      ) |> 
      rename(time_descr = item)
    , by = c('id')
  ) |> 
  mutate(description = ifelse(rank == -1, '.....', description)) |> 
  arrange(group_name, description, time, lastname, firstname, id, rank) 

df_long_tm
```


## Default Orders

```{r}
fs_w_default = NA
fs_t_default = NA
fsa_default = 'Foster, Bill [9]'
fsb_default = NA
fsc_w_default = NA
fsc_t_default = NA
fsd_default = NA
fsm_w_default = NA
fsm_t_default = NA
uca_default = NA
ucb_default = NA
ucm_default = NA
kwa_default = NA
kwb_default = NA
kwm_default = NA

fs_w_keep = NA
fs_t_keep = NA
fsa_keep = TRUE
fsb_keep = NA
fsc_w_keep = NA
fsc_t_keep = NA
fsd_keep = NA
fsm_w_keep = NA
fsm_t_keep = NA
uca_keep = NA
ucb_keep = NA
ucm_keep = NA
kwa_keep = NA
kwb_keep = NA
kwm_keep = NA

# shares = c('Fair Shares Wednesday Pickup', 'Fair Shares Thursday Pickup',
#            'FSA', 'FSB', 'FSC-W', 'FSC-T', 'FSD', 'FSMini-w', 'FSMini-t',
#            'UCA', 'UCB', 'UCM', 'KWA', 'KWB', 'KWM'
#            )
shares = sh_shares$group_name

df_defaults = data.frame(group_name = shares
                         ,name_long = c(fs_w_default, fs_t_default, 
                                        fsa_default, fsb_default, 
                                        fsc_w_default, fsc_t_default, fsd_default, fsm_w_default, fsm_t_default, 
                                        uca_default, ucb_default, ucm_default, 
                                        kwa_default, kwb_default, kwm_default
                                        )
                         ,keep_remove = c(fs_w_keep, fs_t_keep, 
                                        fsa_keep, fsb_keep, 
                                        fsc_w_keep, fsc_t_keep, fsd_keep, fsm_w_keep, fsm_t_keep, 
                                        uca_keep, ucb_keep, ucm_keep, 
                                        kwa_keep, kwb_keep, kwm_keep)
                         )


  
default_customers = df_long_tm |> 
  inner_join(df_long_tm |> 
              inner_join(df_defaults |> 
                           filter(!is.na(name_long))
                         , by = c('group_name', 'name_long')
                         ) |> 
              filter(rank >= 3) |> 
              select(id, group_name, item) |> 
              distinct() |> 
              group_by(id) |> 
              mutate(rank_v = rank(row_number()),
                     default_rows= max(rank_v)
                     ) |>
              ungroup() |> 
              select(-id, -rank_v)
            , by = c('group_name', 'item')
            ) |> 
  filter(rank >= 3) |> 
  select(id, name_long, group_name, item, default_rows) |> 
  distinct() |> 
  group_by(id) |> 
  mutate(rank_v = rank(row_number()),
         customer_rows = max(rank_v)
         ) |>
  ungroup() |> 
  filter(default_rows == customer_rows) |> 
  left_join(df_defaults |> 
              filter(!is.na(name_long))
            , by = c('group_name', 'name_long')
            ) |> 
  mutate(keep_remove = ifelse(is.na(keep_remove), TRUE, keep_remove)) |> 
  select(id, keep_remove) |> 
  distinct() 
  

df_long_def = df_long_tm |> 
  filter(id %in% (default_customers |> filter(keep_remove == TRUE))$id) |> 
  filter(rank <= 2) |> 
  rbind(df_long_tm |> 
          filter(id %in% (default_customers |> filter(keep_remove == TRUE))$id) |> 
          filter(rank >= 3) |> 
          mutate(quantity = NA,
                 item = 'DEFAULT TRADEABLE ITEMS') |> 
          distinct()
  ) |> 
  rbind(df_long_tm |> 
          filter(!id %in% default_customers$id)
  ) |> 
  arrange(group_name, description, time, lastname, firstname, id, rank)
  
df_long_def |> 
  inner_join(default_customers
             , by = c('id')
             ) |> 
  select(group_name, lastname, firstname, id, keep_in_output = keep_remove) |> 
  distinct()

```


## Delete List

```{r}
# delete_list_permanent = c('1 $ New Freezer Donation','1 $ $ for green bags donation','1 $ Food for Ferals Donation','1 $ Food For FS Cats Donation','1 $ Food Pantry Donation','1 $ Freezer Repair Donation','1 $ Paper for Paper - Donation','1 $ Paper for Plastic Donation','1 Each Extra Credit')

delete_list_permanent = sh_delete$item

delete_list_items = df_long_def |> 
  filter(item %in% delete_list_permanent) |> 
  group_by(item) |> 
  summarise(Count = n())

delete_list_items

delete_no_share = df_long_def |> 
  inner_join(df_long_def |> 
               filter(item %in% c('1 No Share - Order Only (even wk)',
                                  '1 No Share - Order Only (odd wk)')
                      ) |> 
               select(id) |> 
               distinct()
             , by = c('id')
             ) |> 
  group_by(id) |> 
  mutate(rank_v = rank(row_number()),
         rows= max(rank_v)
         ) |>
  ungroup() |> 
  filter(rows == 1) |> 
  select(id) |> 
  distinct()

df_long_def |> 
  filter(id %in% delete_no_share$id) |> 
  select(group_name, description, time, lastname, firstname, item) |> 
  distinct()

df_long_del = df_long_def |> 
  filter(!item %in% delete_list_permanent) |> 
  filter(!id %in% delete_no_share$id)

df_long_del |> head(20)

```

## Highlight Share / customer names (via Google Sheets)

```{r eval=FALSE}
df_long_sh_color = df_long_del |> 
  left_join(sh_shares
            , by = c('group_name')
            ) |> 
  mutate(highlight_color_rgb = ifelse(rank <= 0, highlight_color_rgb, NA))

write_df = df_long_sh_color |> 
  select(item)

ss = gs4_create(name = 'test', sheets = write_df )

range_delete(ss, range = "1") # remove column header

test_color = df_long_sh_color |> 
  mutate(ss_cell = paste0('A',row_number())) |> 
  filter(!is.na(highlight_color_rgb)) #|> 
  # group_by(highlight_color_rgb) |> 
  # summarise(ss_cells = toString(ss_cell)) |> 
  # ungroup()

for (i in (test_color |> select(highlight_color_rgb) |> distinct() |> pull())) {
  print(i)
  c = data.frame(c = str_replace_all(
                      str_replace_all(
                        str_replace_all(
                          str_replace_all(
                            i
                          ,'rgb','')
                        ,'\\(','')
                      ,'\\)','')
                    ,' ',''))

  c = c |> 
    separate(c, into = c('r','g','b')) |> 
    mutate(r = as.integer(r)
           ,g = as.integer(g)
           ,b = as.integer(b)
           )
  
  color_background <- googlesheets4:::CellData(
    userEnteredFormat = googlesheets4:::new(
      "CellFormat",
      backgroundColor = googlesheets4:::new(
        "Color",
        red = c$r[1] / 255, green = c$g[1] / 255, blue = c$b[1] / 255
      )
      # ,textFormat = googlesheets4:::new(
      #   "Bold"
      #   , TRUE
      # )
    )
  )
  for (j in (test_color |> filter(highlight_color_rgb == i) |> select(ss_cell) |> distinct() |> pull())) {
    range_flood(ss, range = j, cell = color_background)
  }

}

library(googledrive)

drive_auth(email = '')

fldr = googledrive::drive_find(type = "folder", pattern = "customer_order_list_drop_location_test")

googledrive::drive_mv(ss, path = fldr, name = 'test')

```

## Highlight Share / customer names (via Excel)

```{r}

df_long_sh_color = df_long_del |> 
  left_join(sh_shares
            , by = c('group_name')
            ) |> 
  mutate(highlight_color_hex = ifelse(rank <= 0, highlight_color_hex, NA))

write_df = df_long_sh_color |> 
  select(item)

wb <- createWorkbook(title = 'test')
addWorksheet(wb, "testing")
writeData(wb, "testing", write_df, colNames = FALSE)
#deleteData(wb, "testing", cols = 1, rows = 1)

test_color = df_long_sh_color |> 
  mutate(ss_cell = row_number()) |> 
  filter(!is.na(highlight_color_hex)) #|> 
  # group_by(highlight_color_hex) |> 
  # summarise(ss_cells = toString(ss_cell)) |> 
  # ungroup()

setColWidths(wb, "testing", cols = 1:2, widths = 44)

for (i in (test_color |> select(highlight_color_hex) |> distinct() |> pull())) {
  print(i)
  bhfill_style <- createStyle(bgFill = i, halign = "center", textDecoration = "bold") #having trouble with centering text in column width

  for (j in (test_color |> filter(highlight_color_hex == i) |> select(ss_cell) |> distinct() |> pull())) {
    conditionalFormatting(wb, "testing", cols = 1, rows = j, rule = "!=0", style = bhfill_style)
  }

}

openXL(wb)
```



```{r}
emoji_list = c(emo::ji("poop"), emo::ji("cat"), emo::ji("dog"))
emoji_list

```

