---
title: "R Notebook"
output: html_notebook
---

## Set directory and libraries

```{r}
directory = 'E:/Documents/fair_shares_ds_projects/FS_P003_Customer_Order_List' #desktop
# directory = 'C:/Users/Robert/Documents/_ds_fairshares/FS_P003_Customer_Order_List' #laptop
setwd(directory)

library(tidyverse)
library(DT)
library(googlesheets4)
library(openxlsx)
library(emoji)
library(emo)
```

## load data file

```{r}
file_name = 'Member Pick-up Details-03_23_2022.csv'
# file_name = 'Member Pick-up Details-06_09_2021.csv'
df_orig = read.csv(paste0(directory,'/farmigo_downloads/',file_name)) |> 
  rename_all(tolower) |> 
  rename(group_name = pickup.site, firstname = first.name, lastname = last.name) |> 
  mutate(id = row_number())
```

## connect to settings sheet

```{r}
gs4_auth(email = "")
```

## load settings data

```{r}
sh_shares = range_read('1pEEGA3mawQWmgDtIjJmpBMPws8_-EyEqPtQlucGVlNQ'
                ,sheet = 'shares'
                ,col_types = 'ccc--'
                ,skip = 1
)

sh_delete = range_read('1pEEGA3mawQWmgDtIjJmpBMPws8_-EyEqPtQlucGVlNQ'
                ,sheet = 'delete'
                ,col_types = 'c'
)
```

## Make data long and separate date to be processed without quantity

```{r}
df_orig_long = df_orig  |>  
  mutate(order = strsplit(as.character(order), ",")) |>
  unnest(order) |> 
  mutate(pickuptime = ifelse(str_detect(order, "Pickup Time"), 2, NA),
         order = trimws(order),
         item_original = order
         ) |> 
  separate(order, into = c('quantity','item'), sep = 'x', extra = "merge") |> 
  mutate(item = ifelse(is.na(item) & !is.na(quantity), quantity, item)
         ,quantity = ifelse(item == quantity, NA, quantity)
         ,group_bool = ifelse(is.na(quantity) & !is.na(item), 1, NA)
         ,rank = ifelse(!is.na(group_bool), group_bool,
                        ifelse(!is.na(pickuptime), pickuptime, 3))
         ,name_long = paste0(lastname,', ',firstname,' [',id,']')
         ) |> 
  select(-group_bool, -pickuptime) |> 
  rbind(df_orig |> #bringing in a new row for each group_name
          select(group_name) |> 
          distinct() |> 
          mutate(firstname = '0'
                 ,lastname = '0'
                 ,quantity = NA
                 ,item = group_name
                 ,id = 0
                 ,item_original = group_name
                 ,rank = -1
                 ,name_long = paste0(lastname,', ',firstname,' [',id,']')
                  )
        ) |> 
    rbind(df_orig |> #bringing in a new row for each member name
          select(group_name, firstname, lastname, id) |> 
          distinct() |> 
          mutate(quantity = NA
                 ,item = paste0(lastname,', ',firstname)
                 ,rank = 0
                 ,item_original = item
                 ,name_long = paste0(lastname,', ',firstname,' [',id,']')
                  ) |> 
          select(group_name, firstname, lastname, quantity, item, id, item_original, rank, name_long)
        ) |> 
    rbind(df_orig |> #bringing in a new spacer row for each member name
          select(group_name, firstname, lastname, id) |> 
          distinct() |> 
          mutate(quantity = NA
                 ,item = NA
                 ,rank = 4
                 ,item_original = NA
                 ,name_long = paste0(lastname,', ',firstname,' [',id,']')
                  ) |> 
          select(group_name, firstname, lastname, quantity, item, id, item_original, rank, name_long)
        ) |> 
  arrange(group_name, lastname, firstname, id, rank) 

df_orig_long

```

## Pickup Times found

```{r}
pickup_time = df_orig_long |> 
  filter(rank == 2) |> 
  group_by(Time = item) |> 
  summarise(count = n()) |> 
  ungroup() |> 
  mutate(val = Time) |> 
  separate(val, into = c('q','time','description'), sep = ' ', extra = "merge") |> 
  arrange(description, time, q) 

pickup_time_counts = pickup_time |> 
  select(Time, count)

pickup_time_counts

df_long_tm = df_orig_long |> 
  left_join(
    df_orig_long |> 
      filter(rank == 2) |> 
      select(id, item) |> 
      distinct() |> 
      left_join(pickup_time |> 
                  select(item = Time, description, time)
                , by = c('item')
      ) |> 
      rename(time_descr = item)
    , by = c('id')
  ) |> 
  mutate(description = ifelse(rank == -1, '.....', description)) |> 
  arrange(group_name, description, time, lastname, firstname, id, rank) 

df_long_tm
```


## Default Orders

```{r}
fs_w_default = NA
fs_t_default = NA
fsa_default = 'Foster, Bill [9]'
fsb_default = NA
fsc_w_default = NA
fsc_t_default = NA
fsd_default = NA
fsm_w_default = NA
fsm_t_default = NA
uca_default = NA
ucb_default = NA
ucm_default = NA
kwa_default = NA
kwb_default = NA
kwm_default = NA

fs_w_keep = NA
fs_t_keep = NA
fsa_keep = TRUE
fsb_keep = NA
fsc_w_keep = NA
fsc_t_keep = NA
fsd_keep = NA
fsm_w_keep = NA
fsm_t_keep = NA
uca_keep = NA
ucb_keep = NA
ucm_keep = NA
kwa_keep = NA
kwb_keep = NA
kwm_keep = NA

# shares = c('Fair Shares Wednesday Pickup', 'Fair Shares Thursday Pickup',
#            'FSA', 'FSB', 'FSC-W', 'FSC-T', 'FSD', 'FSMini-w', 'FSMini-t',
#            'UCA', 'UCB', 'UCM', 'KWA', 'KWB', 'KWM'
#            )
shares = sh_shares$group_name

df_defaults = data.frame(group_name = shares
                         ,name_long = c(fs_w_default, fs_t_default, 
                                        fsa_default, fsb_default, 
                                        fsc_w_default, fsc_t_default, fsd_default, fsm_w_default, fsm_t_default, 
                                        uca_default, ucb_default, ucm_default, 
                                        kwa_default, kwb_default, kwm_default
                                        )
                         ,keep_remove = c(fs_w_keep, fs_t_keep, 
                                        fsa_keep, fsb_keep, 
                                        fsc_w_keep, fsc_t_keep, fsd_keep, fsm_w_keep, fsm_t_keep, 
                                        uca_keep, ucb_keep, ucm_keep, 
                                        kwa_keep, kwb_keep, kwm_keep)
                         )


  
default_customers_all = df_long_tm |> 
  left_join(df_long_tm |> 
              inner_join(df_defaults |> 
                           filter(!is.na(name_long))
                         , by = c('group_name', 'name_long')
                         ) |> 
              filter(rank == 3) |> 
              select(id, group_name, item_original) |> 
              distinct() |> 
              group_by(id) |> 
              mutate(rank_v = rank(row_number()),
                     default_rows= max(rank_v)
                     ) |>
              ungroup() |> 
              select(-id, -rank_v)
            , by = c('group_name', 'item_original')
            ) |> 
  filter(rank == 3) |> 
  select(id, name_long, group_name, item_original, default_rows) |> 
  distinct() |> 
  group_by(id) |> 
  mutate(rank_v = sum(ifelse(!is.na(default_rows), 1, 0)),
         customer_rows = max(rank_v),
         rank_n_full = ifelse(!is.na(default_rows), rank(row_number()), 0),
         customer_n_full_rows = max(rank_n_full),
         n_full_rows = sum(ifelse(rank_n_full == 0, 1, 0))
         ) |>
  ungroup() 

default_customers_full_match = default_customers_all |> 
  filter(default_rows == customer_rows & n_full_rows == 0) |> 
  left_join(df_defaults |> 
              filter(!is.na(name_long))
            , by = c('group_name', 'name_long')
            ) |> 
  mutate(keep_remove = ifelse(is.na(keep_remove), TRUE, keep_remove)) |> 
  select(id, keep_remove) |> 
  distinct() 

default_customers_match_w_extras = default_customers_all |> 
  filter(default_rows == (customer_n_full_rows - n_full_rows) & n_full_rows > 0) |> 
  select(id) |> 
  distinct() |> 
  left_join(default_customers_all |> 
              filter(is.na(default_rows)) |> 
              select(id, item_original)
              , by = c('id')
  ) |> 
  mutate(keep_remove =  TRUE) |> 
  select(id, item_original, keep_remove) |> 
  distinct() 
  

df_long_def = df_long_tm |> #bring in default trading member names
  filter(id %in% (default_customers_full_match |> filter(keep_remove == TRUE))$id
         | id %in% (default_customers_match_w_extras |> filter(keep_remove == TRUE))$id
           ) |> 
  filter(rank <= 2) |> 
  select(-item_original) |> 
  rbind(df_long_tm |>  #bring in Default trading item row
          filter(id %in% (default_customers_full_match |> filter(keep_remove == TRUE))$id
                 | id %in% (default_customers_match_w_extras |> filter(keep_remove == TRUE))$id
            ) |> 
          filter(rank >= 3) |> 
          mutate(quantity = NA,
                 item = ifelse(rank == 3, 'DEFAULT TRADEABLE ITEMS', item)
                 ) |> 
          select(-item_original) |> 
          distinct()
  ) |> 
  rbind(df_long_tm |>  #bring in all members not in default member list
          select(-item_original) |> 
          filter(!id %in% (default_customers_full_match |> filter(keep_remove == TRUE))$id
                 & !id %in% (default_customers_match_w_extras |> filter(keep_remove == TRUE))$id
                 )
  ) |> 
  rbind(df_long_tm |>  #bring in items that have a default item match but have extra sales
          inner_join(default_customers_match_w_extras |> 
                       select(-keep_remove)
                    , by = c('id','item_original')
                     ) |> 
          select(-item_original) 
  ) |> 
  arrange(group_name, description, time, lastname, firstname, id, rank)
  
df_long_def |> 
  inner_join(default_customers_match_w_extras |> 
             select(-item_original) |> 
             mutate(extras = TRUE) |> 
             distinct() |> 
             rbind(default_customers_full_match |> 
                     mutate(extras = FALSE))
             , by = c('id')
             ) |> 
  select(group_name, lastname, firstname, id, keep_in_output = keep_remove, extras) |> 
  distinct()

```


## Delete List

```{r}
# delete_list_permanent = c('1 $ New Freezer Donation','1 $ $ for green bags donation','1 $ Food for Ferals Donation','1 $ Food For FS Cats Donation','1 $ Food Pantry Donation','1 $ Freezer Repair Donation','1 $ Paper for Paper - Donation','1 $ Paper for Plastic Donation','1 Each Extra Credit')

delete_list_permanent = sh_delete$item

delete_list_items = df_long_def |> 
  filter(item %in% delete_list_permanent) |> 
  group_by(item) |> 
  summarise(Count = n())

delete_list_items

delete_no_share = df_long_def |> 
  inner_join(df_long_def |> 
               filter(item %in% c('1 No Share - Order Only (even wk)',
                                  '1 No Share - Order Only (odd wk)')
                      ) |> 
               select(id) |> 
               distinct()
             , by = c('id')
             ) |> 
  group_by(id) |> 
  mutate(rank_v = rank(row_number()),
         rows= max(rank_v)
         ) |>
  ungroup() |> 
  filter(rows == 1) |> 
  select(id) |> 
  distinct()

df_long_def |> 
  filter(id %in% delete_no_share$id) |> 
  select(group_name, description, time, lastname, firstname, item) |> 
  distinct()

df_long_del = df_long_def |> 
  filter(!item %in% delete_list_permanent) |> 
  filter(!id %in% delete_no_share$id)

df_long_del |> head(20)

```


## Optimize orders to two columns

```{r}
opt_group = df_long_del |> 
  ungroup() |> 
  filter(rank >= 0) |> 
  group_by(group_name, description, time, lastname, firstname, id) |> 
  summarise(n = n()) |>  
  ungroup() |> 
  arrange(group_name, description, time, lastname, firstname, desc(n))

group_names = df_long_del |>  
  ungroup() |> 
  select(group_name) |> 
  distinct()

column1 = as.data.frame(NULL)
column2 = as.data.frame(NULL)
row_max = 45 ##one minus the max amount of rows per sheet in print process
g_name = NULL
for (g in 1:dim(group_names)[1]) {
  g_name = group_names$group_name[g]
  opt_grouped = opt_group |> 
    filter(group_name == g_name)
  page = 1
  c1_rows = 0
  c2_rows = 0
  c1_cust = 0
  c2_cust = 0
  for (i in 1:dim(opt_grouped)[1]) {
    if (dim(column1)[1] == 0 & dim(column2)[1] == 0 & i == 1) {
      column1 = column1 %>% 
        rbind(opt_grouped[i,] %>% 
                mutate(page_n = page
                       )
              )
      c1_rows = column1$n[dim(column1)[1]]
      c1_cust = 1
    } else {
      if (floor((opt_grouped$n[i] + c1_rows)/row_max) > 0 & floor((opt_grouped$n[i] + c2_rows)/row_max) > 0) {
        page = page+1
        column1 = column1 %>% 
          rbind(opt_grouped[i,] %>% 
                mutate(page_n = page
                       )
              )
        c1_rows = column1$n[dim(column1)[1]]
        c2_rows = 0
        c1_cust = 1
        c2_cust = 0
      } else if (floor((opt_grouped$n[i] + c1_rows)/row_max) > 0 & floor((opt_grouped$n[i] + c2_rows)/row_max) == 0) {
        column2 = column2 %>% 
          rbind(opt_grouped[i,] %>% 
                mutate(page_n = page
                       )
              )
        c2_rows = c2_rows + column2$n[dim(column2)[1]]
        c2_cust = c2_cust + 1
      } else if (c1_cust > c2_cust) {
        column2 = column2 %>% 
          rbind(opt_grouped[i,] %>% 
                mutate(page_n = page
                       )
              )
        c2_rows = c2_rows + column2$n[dim(column2)[1]]
        c2_cust = c2_cust + 1
      } else {
        column1 = column1 %>% 
          rbind(opt_grouped[i,] %>% 
                mutate(page_n = page
                       )
              )
        c1_rows = c1_rows + column1$n[dim(column1)[1]]
        c1_cust = c1_cust + 1
      }
    }
    # print(opt_grouped$n[i])
  }
}

group_name_additions_c1 = df_long_del %>% 
  ungroup() |> 
  filter(rank < 0) |> 
  mutate(n = 1) |> 
  select(group_name, description, time, lastname, firstname, id, n) |> 
  left_join(column1 |> 
              select(group_name, page_n) |> 
              distinct()
            , by = c('group_name')
            ) |> 
  rbind(column1) |> 
  arrange(group_name, page_n, description, time, lastname, firstname, desc(n))

group_name_additions_c2 = df_long_del %>% 
  ungroup() |> 
  filter(rank < 0) |> 
  mutate(n = 1) |> 
  select(group_name, description, time, lastname, firstname, id, n) |> 
  left_join(column2 |> 
              select(group_name, page_n) |> 
              distinct()
            , by = c('group_name')
            ) |> 
  rbind(column2) |> 
  arrange(group_name, page_n, description, time, lastname, firstname, desc(n))
  
row_df = data.frame(row_n = 0:row_max+1)
print_full = column1 |> 
  select(group_name, page_n) |> 
  distinct() |> 
  full_join(row_df, by = character()
            )

column1_w_groups = group_name_additions_c1 |> 
  select(id, n, page_n, group_name_col = group_name) |> 
  left_join(df_long_del |> 
              ungroup() |> 
              filter(rank >= 0)
            , by = c('id')
            ) |> 
  mutate(item = ifelse(is.na(rank), group_name_col, item),
         group_name = ifelse(is.na(rank), group_name_col, group_name),
         rank = ifelse(is.na(rank), -1, rank)
         ) |> 
  select(-group_name_col) |> 
  group_by(group_name, page_n) |> 
  mutate(row_n = rank(row_number()))

column2_w_groups = group_name_additions_c2 |> 
  select(id, n, page_n, group_name_col = group_name) |> 
  left_join(df_long_del |> 
              ungroup() |> 
              filter(rank >= 0)
            , by = c('id')
            ) |> 
  mutate(item = ifelse(is.na(rank), group_name_col, item),
         group_name = ifelse(is.na(rank), group_name_col, group_name),
         rank = ifelse(is.na(rank), -1, rank)
         ) |> 
  select(-group_name_col) |> 
  group_by(group_name, page_n) |> 
  mutate(row_n = rank(row_number()))

column1_print = print_full |> 
  left_join(column1_w_groups
            , by = c('group_name', 'page_n', 'row_n')
  )

column2_print = print_full |> 
  left_join(column2_w_groups
            , by = c('group_name', 'page_n', 'row_n')
  )

```

## adding in symbols or emojis

```{r}
# test = data.frame(emoji::emoji_name)
# test = test |> rownames_to_column()

# df_symbol_inputs = data.frame(match_name = c('equal', 'contains', 'contains')
#                              ,text_name = c('1 Dozen Eggs', 'MILK', 'Chocolate')
#                              ,freeform_text = c(NA, '[***]', NA)
#                              ,emoji_name = c(emo::ji('chicken'), emo::ji('cow'), emo::ji('chocolate'))
#                              )

df_symbol_inputs_milk = data.frame(match_name = c('contains', 'contains', 'contains', 'contains', 'contains', 'contains', 'contains', 'contains', 'contains', 'contains', 'contains')
                             ,text_name = c('Milk - 2%','Milk - Chocolate','Milk - Creamline','Milk - Skim','Milk - Whole', '2% MILK', 'Chocolate MILK', 'Creamline MILK', 'Skim MILK', 'Whole MILK', 'Whole Milk - o')
                             ,freeform_text = c('[*]', '[*]', '[*]', '[*]', '[*]','[*]', '[*]', '[*]', '[*]', '[*]', '[*]')
                             ,emoji_name = c(emo::ji('milk_glass'), emo::ji('milk_glass'), emo::ji('milk_glass'), emo::ji('milk_glass'), emo::ji('milk_glass'), emo::ji('milk_glass'), emo::ji('milk_glass'), emo::ji('milk_glass'), emo::ji('milk_glass'), emo::ji('milk_glass'), emo::ji('milk_glass'))
                             )

df_symbol_inputs_pizza = data.frame(match_name = c('contains', 'contains', 'contains', 'contains', 'contains', 'contains', 'contains', 'contains')
                             ,text_name = c('Pizza - Cheese','Pizza - Deluxe','Pizza - Four Meat','Pizza - Hot Chicken','Pizza - Pepperoni','Pizza - Sausage Pepperoni','Pizza - Tomato Basil Garlic','Pizza - Veggie')
                             ,freeform_text = c('[**]', '[**]', '[**]', '[**]', '[**]', '[**]', '[**]', '[**]')
                             ,emoji_name = c(emo::ji('pizza'), emo::ji('pizza'), emo::ji('pizza'), emo::ji('pizza'), emo::ji('pizza'), emo::ji('pizza'), emo::ji('pizza'), emo::ji('pizza'))
                             )

df_symbol_inputs_other = data.frame(match_name = c('contains', 'contains', 'contains','contains','contains')
                             ,text_name = c('FF Dish - Creole Shrimp & Okra','Pork - Andouille links','Raw Milk Aged Cheddar','Pickup Time','Schlafly Beer')
                             ,freeform_text = c('[**]', '[andouille]', '[1]',NA, NA)
                             ,emoji_name = c(emo::ji('fried_shrimp'), NA, emo::ji('cheese'), emo::ji('clock3'), emo::ji('beer'))
                             )
df_symbol_inputs = df_symbol_inputs_milk |> 
  rbind(df_symbol_inputs_pizza) |> 
  rbind(df_symbol_inputs_other)

symbol_addition = function(item_n, match_n, text_n, ff_n, em_n) {
  ifelse((!is.na(ff_n)) & (!is.na(em_n)),
      ifelse(match_n == 'equal', ifelse(item_n == text_n, paste0(em_n, ff_n), NA),
      ifelse(match_n == 'contains', ifelse(str_detect(item_n, text_n), paste0(em_n, ff_n), NA),
      ifelse(match_n == 'starts with', ifelse(startsWith(item_n, text_n), paste0(em_n, ff_n), NA),
      ifelse(match_n == 'ends with', ifelse(endsWith(item_n, text_n), paste0(em_n, ff_n), NA)
             , NA))))
  ,ifelse((!is.na(ff_n)), 
      ifelse(match_n == 'equal', ifelse(item_n == text_n, paste0(ff_n), NA),
      ifelse(match_n == 'contains', ifelse(str_detect(item_n, text_n), paste0(ff_n), NA),
      ifelse(match_n == 'starts with', ifelse(startsWith(item_n, text_n), paste0(ff_n), NA),
      ifelse(match_n == 'ends with', ifelse(endsWith(item_n, text_n), paste0(ff_n), NA)
             , NA))))
  ,ifelse((!is.na(em_n)) , 
      ifelse(match_n == 'equal', ifelse(item_n == text_n, paste0(em_n), NA),
      ifelse(match_n == 'contains', ifelse(str_detect(item_n, text_n), paste0(em_n), NA),
      ifelse(match_n == 'starts with', ifelse(startsWith(item_n, text_n), paste0(em_n), NA),
      ifelse(match_n == 'ends with', ifelse(endsWith(item_n, text_n), paste0(em_n), NA)
             , NA))))   
  , NA)))
}

symbol_search_c1 = column1_print |> 
  select(item) |> 
  distinct() |> 
  full_join(df_symbol_inputs
            , by = character()
            ) |> 
  mutate(symbol_text = symbol_addition(item, match_name, text_name, freeform_text, emoji_name)) |> 
  filter(!is.na(symbol_text)) |> 
  select(item, symbol_text) |> 
  arrange(item, symbol_text) |> 
  group_by(item) |> 
  mutate(symbol_text = paste0(symbol_text, collapse = "")) |> 
  ungroup() |> 
  distinct()

df_long_symbol_c1 = column1_print |> 
  left_join(symbol_search_c1
            , by = c('item')
            ) |> 
  mutate(quantity = ifelse(is.na(quantity), '', as.character(quantity))
           , item_symbol = ifelse(quantity == '', item, paste0(quantity,'x',item))
           , item_symbol = ifelse(is.na(symbol_text), item_symbol, paste0(symbol_text, item_symbol))
         )

symbol_search_c2 = column2_print |> 
  select(item) |> 
  distinct() |> 
  full_join(df_symbol_inputs
            , by = character()
            ) |> 
  mutate(symbol_text = symbol_addition(item, match_name, text_name, freeform_text, emoji_name)) |> 
  filter(!is.na(symbol_text)) |> 
  select(item, symbol_text) |> 
  arrange(item, symbol_text) |> 
  group_by(item) |> 
  mutate(symbol_text = paste0(symbol_text, collapse = "")) |> 
  ungroup() |> 
  distinct()

df_long_symbol_c2 = column2_print |> 
  left_join(symbol_search_c2
            , by = c('item')
            ) |> 
  mutate(quantity = ifelse(is.na(quantity), '', as.character(quantity))
           , item_symbol = ifelse(quantity == '', item, paste0(quantity,'x',item))
           , item_symbol = ifelse(is.na(symbol_text), item_symbol, paste0(symbol_text, item_symbol))
         )

```

## Highlight Share / customer names (via Excel)

```{r}

df_long_sh_color_c1 = df_long_symbol_c1 |> 
  left_join(sh_shares
            , by = c('group_name')
            ) |> 
  mutate(highlight_color_hex = ifelse(rank <= 0, highlight_color_hex, NA))

df_long_sh_color_c2 = df_long_symbol_c2 |> 
  left_join(sh_shares
            , by = c('group_name')
            ) |> 
  mutate(highlight_color_hex = ifelse(rank <= 0, highlight_color_hex, NA))

write_df = df_long_sh_color_c1 |>
  select(item_1 = item_symbol) |>
  cbind(
    df_long_sh_color_c2 |> 
      select(item_2 = item_symbol)
  )

wb <- createWorkbook(title = 'TestFile')
addWorksheet(wb, "testing")
writeData(wb, "testing", write_df, colNames = FALSE)

setColWidths(wb, "testing", cols = 1:2, widths = 40)
modifyBaseFont(wb, fontSize = 12, fontColour = "black", fontName = "Calibri")

test_color_c1 = df_long_sh_color_c1 |> 
  mutate(ss_cell = row_number()) |> 
  filter(!is.na(highlight_color_hex)) 

for (i in (test_color_c1 |> select(highlight_color_hex) |> distinct() |> pull())) {
  print(i)
  bhfill_style <- createStyle(bgFill = i, textDecoration = "bold") 

  for (j in (test_color_c1 |> filter(highlight_color_hex == i) |> select(ss_cell) |> distinct() |> pull())) {
    conditionalFormatting(wb, "testing", rule = "!=0", cols = 1, rows = j, style = bhfill_style)
    addStyle(wb, "testing", cols = 1, rows = j, style = createStyle(halign = "center"))
  }

}

test_color_c2 = df_long_sh_color_c2 |> 
  mutate(ss_cell = row_number()) |> 
  filter(!is.na(highlight_color_hex)) 

for (i in (test_color_c2 |> select(highlight_color_hex) |> distinct() |> pull())) {
  print(i)
  bhfill_style <- createStyle(bgFill = i, textDecoration = "bold") 

  for (j in (test_color_c2 |> filter(highlight_color_hex == i) |> select(ss_cell) |> distinct() |> pull())) {
    conditionalFormatting(wb, "testing", rule = "!=0", cols = 2, rows = j, style = bhfill_style)
    addStyle(wb, "testing", cols = 2, rows = j, style = createStyle(halign = "center"))
  }

}

style_xlsx = function(wb_n, sheet, col_n, match, text, colorhex, text_dec_name) {
  if (!is.na(colorhex) & !is.na(text_dec_name)) {  #HIGHLIGHT BACKGROUND AND DECORATE TEXT
    if (match == 'equal') {
      addStyle(wb_n, sheet
           , cols = col_n
           , rows = which(df_long_sh_color$item == text)
           , style = createStyle(fgFill = colorhex
                                 ,textDecoration = text_dec_name)
           )
    } else if (match == 'contains') {
      addStyle(wb_n, sheet
           , cols = col_n
           , rows = which(str_detect(df_long_sh_color$item, pattern = text))
           , style = createStyle(fgFill = colorhex
                                 ,textDecoration = text_dec_name)
           )
    } else if (match == 'starts with') {
      addStyle(wb_n, sheet
           , cols = col_n
           , rows = which(startsWith(df_long_sh_color$item, text))
           , style = createStyle(fgFill = colorhex
                                 ,textDecoration = text_dec_name)
           )
    } else if (match == 'ends with') {
      addStyle(wb_n, sheet
           , cols = col_n
           , rows = which(endsWith(df_long_sh_color$item, text))
           , style = createStyle(fgFill = colorhex
                                 ,textDecoration = text_dec_name)
           )
    } else {
      print('valid match type not determined')
    }
  } else if (!is.na(colorhex)) {    #HIGHLIGHT BACKGROUND ONLY
    if (match == 'equal') {
      addStyle(wb_n, sheet
           , cols = col_n
           , rows = which(df_long_sh_color$item == text)
           , style = createStyle(fgFill = colorhex)
           )
    } else if (match == 'contains') {
      addStyle(wb_n, sheet
           , cols = col_n
           , rows = which(str_detect(df_long_sh_color$item, pattern = text))
           , style = createStyle(fgFill = colorhex)
           )
    } else if (match == 'starts with') {
      addStyle(wb_n, sheet
           , cols = col_n
           , rows = which(startsWith(df_long_sh_color$item, text))
           , style = createStyle(fgFill = colorhex)
           )
    } else if (match == 'ends with') {
      addStyle(wb_n, sheet
           , cols = col_n
           , rows = which(endsWith(df_long_sh_color$item, text))
           , style = createStyle(fgFill = colorhex)
           )
    } else {
      print('valid match type not determined')
    }
  } else if (!is.na(text_dec_name)) {   #DECORATE TEXT ONLY
    if (match == 'equal') {
      addStyle(wb_n, sheet
           , cols = col_n
           , rows = which(df_long_sh_color$item == text)
           , style = createStyle(textDecoration = text_dec_name)
           )
    } else if (match == 'contains') {
      addStyle(wb_n, sheet
           , cols = col_n
           , rows = which(str_detect(df_long_sh_color$item, pattern = text))
           , style = createStyle(textDecoration = text_dec_name)
           )
    } else if (match == 'starts with') {
      addStyle(wb_n, sheet
           , cols = col_n
           , rows = which(startsWith(df_long_sh_color$item, text))
           , style = createStyle(textDecoration = text_dec_name)
           )
    } else if (match == 'ends with') {
      addStyle(wb_n, sheet
           , cols = col_n
           , rows = which(endsWith(df_long_sh_color$item, text))
           , style = createStyle(textDecoration = text_dec_name)
           )
    } else {
      print('valid match type not determined')
    }
  } else {
    print('Need to selet a color or text format type')
  }
  
}
df_long_sh_color = df_long_sh_color_c1
# style_xlsx(wb, "testing", 1, 'equal', "1 Dozen Eggs", '#ffff00', NA)
# style_xlsx(wb, "testing", 1, 'starts with', "64 Oz. Milk - Whole", '#00ffff', NA)
# style_xlsx(wb, "testing", 1, 'ends with', "Green Curly", '#00ff00', NA)

# style_xlsx(wb, "testing", 1, 'contains', "Pickup Time", '#efefef', 'bold')
# style_xlsx(wb, "testing", 1, 'contains', "Pickup Time", NA, 'bold')
style_xlsx(wb, "testing", 1, 'equal', "DEFAULT TRADEABLE ITEMS", NA, 'bold')
style_xlsx(wb, "testing", 1, 'contains', "Pickup Time", NA, 'italic')

df_long_sh_color = df_long_sh_color_c2
# style_xlsx(wb, "testing", 2, 'equal', "1 Dozen Eggs", '#ffff00', NA)
# style_xlsx(wb, "testing", 2, 'starts with', "64 Oz. Milk - Whole", '#00ffff', NA)
# style_xlsx(wb, "testing", 2, 'ends with', "Green Curly", '#00ff00', NA)

# style_xlsx(wb, "testing", 2, 'contains', "Pickup Time", '#efefef', 'bold')
# style_xlsx(wb, "testing", 2, 'contains', "Pickup Time", NA, 'bold')

style_xlsx(wb, "testing", 2, 'equal', "DEFAULT TRADEABLE ITEMS", NA, 'bold')
style_xlsx(wb, "testing", 2, 'contains', "Pickup Time", NA, 'italic')

openXL(wb)

saveWorkbook(wb, "TestFile.xlsx", overwrite = TRUE)
```

